### ISSUE TITLE
Unable to load in SQLite

### ISSUE THREAD

**Issue by tresoldi** [lexibank/tppsr#22]
It is currently impossible to load the database, due to the `Population` property in the `LanguageTable` ( cf. https://cldf.clld.org/v1.0/terms.rdf#LanguageTable ), when working on `lexicore`.

Loading only `tppsr` fails because of foreign key constraint:

```bash
(fresh environment)
$ pip install -e git+https://github.com/lexibank/tppsr.git#egg=lexibank_tppsr
$ cldfbench lexibank.load _
INFO    running load on tppsr ...
Dataset "tppsr" at /home/tresoldi/lexibank/lexicore/env/src/lexibank-tppsr
Traceback (most recent call last):
[...]
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by LinguList** [comment]
If this cannot be loaded into sqlite due to the IntegrityError, isn't this a typical problem for pycldf or pylexibank? Why is this an issue of this repository?

**Comment by xrotwang** [comment]
Hm. I'd say this is a bug/limitation of `pylexibank`.

**Comment by xrotwang** [comment]
As far as I can tell, the problem is the list-valued foreign key `Form_ID` in `ExampleTable`. I guess, the more complex our datasets, the more fragile the "load-into-a-single-db" approach.

I can see two ways out of this dilemma:
- Limit loading of data into a shared DB to core stuff or drop foreign key constraints between non-core tables.
- Switch to a multi-databases setup (see https://stackoverflow.com/a/6824831) - but this may be limited and inefficient.

**Comment by LinguList** [comment]
I'd say: limiting data in shared dbs is also usfeul for SHARING the DB,
right? We need to be explicit in what we want anyway, as uncomparable
stuff is not in our interest...

**Comment by xrotwang** [comment]
Ok, just to confirm: The two list-valued foreign keys `ExampleTable` are the problem here. Dropping them, i.e. removing `propertyUrl` from `Form_ID` and `Concept_ID` and the foreign key constraints in `cldf/cldf-metadata.json` solves the problem.

**Comment by xrotwang** [comment]
The code in `pycldf` loading a single dataset into sqlite gained the functionality to handle list-valued foreign keys at some point - but I think that wasn't ported to `pylexibank.db`. Since that code is a bit complicated anyway, I'd lean towards ignoring such constraints rather than supporting them (which would require creating association tables, etc.)

**Comment by xrotwang** [comment]
@tresoldi I think something like
```
if ds[table, fk.coumnReference[0]].separator:
    continue
```
somewhere here
https://github.com/lexibank/pylexibank/blob/dd81f7d9a9d18b8e4f77bffc169d6f6206ee104b/src/pylexibank/db.py#L182-L212
should do the trick.

**Comment by xrotwang** [comment]
@tresoldi see https://github.com/lexibank/pylexibank/pull/227
